import { useEffect, useRef, useState } from "react";
import { parseOrder, createOrder, fetchOrder } from "./api.js";
import { useVoiceRecorder } from "./useVoiceRecorder.js";
import { WS_BASE, DEMO_MERCHANT_ID } from "./config.js";
import "./chat.css";

function ts() {
  	const d = new Date();
  	return d.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
}

const uid = () => Math.random().toString(36).slice(2, 10);

export default function App() {

	const [messages, setMessages] = useState([
		{ id: uid(), from: "seller", kind: "text", text: "Hi 👋 What would you like to order today?", time: ts() },
	]);
	const [input, setInput] = useState("");
	const [busy, setBusy] = useState(false);
	const [activeOrderId, setActiveOrderId] = useState(null);
	const scrollRef = useRef(null);
	const rec = useVoiceRecorder();

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" });
  }, [messages]);

  useEffect(() => {
    const ws = new WebSocket(`${WS_BASE}/ws?merchant_id=${DEMO_MERCHANT_ID}`);
    ws.onmessage = async (evt) => {
      let msg; try { msg = JSON.parse(evt.data); } catch { return; }
      if (msg.type === "hello") return;
      if (!msg.order_id) return;
      // Only react to our currently-active order for chat noise reasons.
      if (activeOrderId && msg.order_id !== activeOrderId) return;

      if (msg.status === "awaiting_payment") {
        // Fetch fresh order to get the payment link generated by backend-core
        try {
          const o = await fetchOrder(msg.order_id);
          push({ from: "system", kind: "payment", link: o.payment_link,
            amount: o.total_amount, reference: o.opay_tx_reference });
        } catch {
          push({ from: "system", kind: "status", text: "Seller approved your order — payment link coming shortly." });
        }
      } else if (msg.status === "paid") {
        push({ from: "system", kind: "status", text: "✅ Payment confirmed. Preparing your order…" });
      } else if (msg.status === "out_for_delivery") {
        push({ from: "system", kind: "status", text: "🛵 Rider assigned — on the way." });
      } else if (msg.status === "delivered") {
        push({ from: "system", kind: "status", text: "📦 Delivered. Thank you!" });
      } else if (msg.status === "cancelled") {
        push({ from: "system", kind: "status", text: "Order cancelled." });
      }
    };
    return () => {
		// If it's already open, close it safely
		if (ws.readyState === WebSocket.OPEN) {
			ws.close();
		} 
		// If it's still connecting, wait for it to open first, then immediately close it
		else if (ws.readyState === WebSocket.CONNECTING) {
			ws.onopen = () => ws.close();
		}
	};
  }, [activeOrderId]);

	const push = (m) => setMessages((prev) => [...prev, { id: uid(), time: ts(), ...m }]);

	async function sendText() {
		const text = input.trim();
		if (!text) return;
		setInput("");
		push({ from: "customer", kind: "text", text });
		await runParse({ message_text: text }, text);
	}

	async function toggleRecord() {
		if (rec.recording) {
		setBusy(true);
		const audio = await rec.stop();
		if (audio) {
			push({ from: "customer", kind: "audio", url: audio.url });
			await runParse(
			{ audio_base64: audio.base64, audio_mime: audio.mime },
			"(voice note)"
			);
		}
		setBusy(false);
		} else {
		await rec.start();
		}
	}

	async function runParse(payload, rawText) {
		setBusy(true);
		try {
		const { data: parsed, source } = await parseOrder(payload);
		push({ from: "seller", kind: "parsed", parsed, source });

		if (parsed.missing_fields?.length && parsed.follow_up_question) {
			push({ from: "seller", kind: "text", text: parsed.follow_up_question });
		} else {
			const created = await createOrder(parsed, rawText);
			if (created?.id) {
			setActiveOrderId(created.id);
			push({ from: "system", kind: "status",
					text: `Order queued for seller approval · #${created.id.slice(0, 8)}` });
			} else {
			push({ from: "system", kind: "status",
					text: "Order captured (backend offline — not persisted)." });
			}
		}
		} catch (e) {
		push({ from: "seller", kind: "text", text: `Sorry, I couldn't process that (${e.message}).` });
		} finally {
		setBusy(false);
		}
	}

  return (
    <div className="phone">
      <header className="chat-head">
        <div className="avatar">A</div>
        <div>
          <div className="chat-name">Ada Fashion House</div>
          <div className="chat-sub">online · powered by OPay SwiftOrder</div>
        </div>
      </header>

      <main className="chat-body" ref={scrollRef}>
        {messages.map((m) => (
          <Bubble key={m.id} m={m} />
        ))}
        {busy && <div className="typing"><span></span><span></span><span></span></div>}
      </main>

      {rec.error && <div className="mic-warn">⚠ {rec.error}</div>}

      <footer className="chat-input">
        <input
          className="msg-input"
          placeholder="Type a message…"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && sendText()}
          disabled={rec.recording}
        />
        {input.trim() ? (
          <button className="mic-btn send" onClick={sendText} title="Send">➤</button>
        ) : (
          <button
            className={"mic-btn" + (rec.recording ? " recording" : "")}
            onClick={toggleRecord}
            title={rec.recording ? "Stop recording" : "Record voice note"}
          >
            {rec.recording ? "■" : "🎙"}
          </button>
        )}
      </footer>
    </div>
  );
}

function Bubble({ m }) {
  if (m.from === "system") {
    if (m.kind === "payment") {
      return (
        <div className="sys-wrap">
          <div className="sys-card">
            <div className="pay-title">💳 Complete your payment</div>
            <div className="pay-amt">₦{Number(m.amount || 0).toLocaleString()}</div>
            <a className="pay-btn" href={m.link || "#"} target="_blank" rel="noreferrer">
              Pay with OPay →
            </a>
            <div className="pay-ref">ref {m.reference}</div>
            <div className="pay-banner">🔒 Secured by OPay — no screenshots needed</div>
          </div>
        </div>
      );
    }
    return <div className="sys-line">{m.text}<span className="ts">{m.time}</span></div>;
  }

  const side = m.from === "customer" ? "right" : "left";
  return (
    <div className={`bubble-row ${side}`}>
      <div className={`bubble ${side}`}>
        {m.kind === "text" && <span>{m.text}</span>}
        {m.kind === "audio" && <audio controls src={m.url} />}
        {m.kind === "parsed" && <ParsedCard parsed={m.parsed} source={m.source} />}
        <span className="ts">{m.time}{side === "right" ? " ✓✓" : ""}</span>
      </div>
    </div>
  );
}

function ParsedCard({ parsed, source }) {
  return (
    <div className="parsed-card">
      <div className="parsed-title">
        📝 Order draft
        <span className={`chip conf-${parsed.confidence}`}>{parsed.confidence}</span>
        {source === "mock" && <span className="chip mock">mock</span>}
      </div>
      <ul>
        {parsed.items.map((it, i) => (
          <li key={i}>
            <b>{it.qty}×</b> {it.item}
            {it.size ? ` · size ${it.size}` : ""}
            {it.color ? ` · ${it.color}` : ""}
          </li>
        ))}
      </ul>
      <div className="parsed-meta">
        📍 {parsed.delivery_address || <i>(need address)</i>}
        {parsed.delivery_type ? ` · via ${parsed.delivery_type}` : ""}
      </div>
      {parsed.missing_fields?.length ? (
        <div className="parsed-warn">Missing: {parsed.missing_fields.join(", ")}</div>
      ) : (
        <div className="parsed-ok">Sent to seller for approval ✓</div>
      )}
    </div>
  );
}
