import { useEffect, useMemo, useRef, useState } from "react";
import { parseOrder, createOrder, fetchOrder } from "./api.js";
import { useVoiceRecorder } from "./useVoiceRecorder.js";
import { WS_BASE, DEMO_MERCHANT_ID } from "./config.js";
import "./chat.css";

function ts() {
  	const d = new Date();
  	return d.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
}

const uid = () => Math.random().toString(36).slice(2, 10);
const AUTH_KEY = "chatrail.demo-auth";

function getSavedAuth() {
	if (typeof window === "undefined") return null;
	try {
		const raw = window.localStorage.getItem(AUTH_KEY);
		return raw ? JSON.parse(raw) : null;
	} catch {
		return null;
	}
}

export default function App() {
	const [auth, setAuth] = useState(() => getSavedAuth());
	const [mode, setMode] = useState("login");
	const [authForm, setAuthForm] = useState({
		name: "",
		email: "",
		password: "",
		company: "",
	});
	const [authError, setAuthError] = useState("");
	const [authBusy, setAuthBusy] = useState(false);

	useEffect(() => {
		if (!auth || typeof window === "undefined") return;
		window.localStorage.setItem(AUTH_KEY, JSON.stringify(auth));
	}, [auth]);

	const [messages, setMessages] = useState([
		{ id: uid(), from: "seller", kind: "text", text: "Hi 👋 What would you like to order today?", time: ts() },
	]);
	const [input, setInput] = useState("");
	const [busy, setBusy] = useState(false);
	const [activeOrderId, setActiveOrderId] = useState(null);
	const scrollRef = useRef(null);
	const rec = useVoiceRecorder();
	const displayName = useMemo(() => auth?.name || auth?.email || "Guest", [auth]);

  // Auto-scroll once the chat is mounted; auth screen does not render the chat body.
  useEffect(() => {
    if (!auth) return;
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" });
  }, [auth, messages]);

  // WebSocket — same merchant room as the dashboard
  useEffect(() => {
    if (!auth) return;
    const ws = new WebSocket(`${WS_BASE}/ws?merchant_id=${DEMO_MERCHANT_ID}`);
    ws.onmessage = async (evt) => {
    let msg; try { msg = JSON.parse(evt.data); } catch { return; }
    if (msg.type === "hello") return;
    if (!msg.order_id) return;
    // Only react to our currently-active order for chat noise reasons.
    if (activeOrderId && msg.order_id !== activeOrderId) return;

    if (msg.status === "awaiting_payment") {
      // Fetch fresh order to get the payment link generated by backend-core
      try {
      const o = await fetchOrder(msg.order_id);
      push({ from: "system", kind: "payment", link: o.payment_link,
          amount: o.total_amount, reference: o.opay_tx_reference });
      } catch {
      push({ from: "system", kind: "status", text: "Seller approved your order — payment link coming shortly." });
      }
    } else if (msg.status === "paid") {
      push({ from: "system", kind: "status", text: "✅ Payment confirmed. Preparing your order…" });
    } else if (msg.status === "out_for_delivery") {
      push({ from: "system", kind: "status", text: "🛵 Rider assigned — on the way." });
    } else if (msg.status === "delivered") {
      push({ from: "system", kind: "status", text: "📦 Delivered. Thank you!" });
    } else if (msg.status === "cancelled") {
      push({ from: "system", kind: "status", text: "Order cancelled." });
    }
    };
    
	
	return () => {
		// If it's already open, close it safely
		if (ws.readyState === WebSocket.OPEN) {
			ws.close();
		} 
		// If it's still connecting, wait for it to open first, then immediately close it
		else if (ws.readyState === WebSocket.CONNECTING) {
			ws.onopen = () => ws.close();
		}
	};
  }, [auth, activeOrderId]);

	const push = (m) => setMessages((prev) => [...prev, { id: uid(), time: ts(), ...m }]);

	function logout() {
		setAuth(null);
		setAuthForm({ name: "", email: "", password: "", company: "" });
		setAuthError("");
		setMode("login");
		if (typeof window !== "undefined") {
		window.localStorage.removeItem(AUTH_KEY);
		}
	}

	async function submitAuth(e) {
		e.preventDefault();
		setAuthError("");
		setAuthBusy(true);

		try {
			const email = authForm.email.trim().toLowerCase();
			const password = authForm.password.trim();
			if (!email || !password) {
				throw new Error("Email and password are required.");
			}

			if (mode === "register") {
				if (!authForm.name.trim()) throw new Error("Name is required.");
				if (password.length < 6) throw new Error("Password must be at least 6 characters.");
				setAuth({
				name: authForm.name.trim(),
				email,
				company: authForm.company.trim() || "SwiftOrder Merchant",
				});
			} else {
				setAuth({
				name: authForm.name.trim() || email.split("@")[0],
				email,
				company: authForm.company.trim() || "SwiftOrder Merchant",
				});
			}
		} catch (err) {
			setAuthError(err.message);
		} finally {
			setAuthBusy(false);
		}
	}

	if (!auth) {
		return (
		<AuthScreen
			mode={mode}
			setMode={setMode}
			form={authForm}
			setForm={setAuthForm}
			error={authError}
			busy={authBusy}
			onSubmit={submitAuth}
		/>
		);
	}

	async function sendText() {
		const text = input.trim();
		if (!text) return;
		setInput("");
		push({ from: "customer", kind: "text", text });
		await runParse({ message_text: text }, text);
	}

	async function toggleRecord() {
		if (rec.recording) {
		setBusy(true);
		const audio = await rec.stop();
		if (audio) {
			push({ from: "customer", kind: "audio", url: audio.url });
			await runParse(
			{ audio_base64: audio.base64, audio_mime: audio.mime },
			"(voice note)"
			);
		}
		setBusy(false);
		} else {
		await rec.start();
		}
	}

	async function runParse(payload, rawText) {
		setBusy(true);
		try {
		const { data: parsed, source } = await parseOrder(payload);
		push({ from: "seller", kind: "parsed", parsed, source });

		if (parsed.missing_fields?.length && parsed.follow_up_question) {
			push({ from: "seller", kind: "text", text: parsed.follow_up_question });
		} else {
			const created = await createOrder(parsed, rawText);
			if (created?.id) {
			setActiveOrderId(created.id);
			push({ from: "system", kind: "status",
					text: `Order queued for seller approval · #${created.id.slice(0, 8)}` });
			} else {
			push({ from: "system", kind: "status",
					text: "Order captured (backend offline — not persisted)." });
			}
		}
		} catch (e) {
		push({ from: "seller", kind: "text", text: `Sorry, I couldn't process that (${e.message}).` });
		} finally {
		setBusy(false);
		}
	}

  return (
    <div className="phone">
      <header className="chat-head">
        <div className="avatar">{displayName.slice(0, 1).toUpperCase()}</div>
        <div>
          <div className="chat-name">Ada Fashion House</div>
          <div className="chat-sub">{displayName} · online · powered by OPay SwiftOrder</div>
        </div>
        <button className="auth-link" onClick={logout} type="button">
          Sign out
        </button>
      </header>

      <main className="chat-body" ref={scrollRef}>
        {messages.map((m) => (
          <Bubble key={m.id} m={m} />
        ))}
        {busy && <div className="typing"><span></span><span></span><span></span></div>}
      </main>

      {rec.error && <div className="mic-warn">⚠ {rec.error}</div>}

      <footer className="chat-input">
        <input
          className="msg-input"
          placeholder="Type a message…"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && sendText()}
          disabled={rec.recording}
        />
        {input.trim() ? (
          <button className="mic-btn send" onClick={sendText} title="Send">➤</button>
        ) : (
          <button
            className={"mic-btn" + (rec.recording ? " recording" : "")}
            onClick={toggleRecord}
            title={rec.recording ? "Stop recording" : "Record voice note"}
          >
            {rec.recording ? "■" : "🎙"}
          </button>
        )}
      </footer>
    </div>
  );
}

function AuthScreen({ mode, setMode, form, setForm, error, busy, onSubmit }) {
  const isRegister = mode === "register";

  return (
    <div className="auth-shell">
      <div className="auth-card">
        <div className="auth-badge">SwiftOrder</div>
        <h1>{isRegister ? "Create your merchant account" : "Welcome back"}</h1>
        <p>
          {isRegister
            ? "Set up your store account to start handling live chat orders, approvals, and deliveries."
            : "Sign in to continue managing chats and orders from your demo storefront."}
        </p>

        <div className="auth-tabs" role="tablist" aria-label="Authentication mode">
          <button
            type="button"
            className={mode === "login" ? "auth-tab active" : "auth-tab"}
            onClick={() => setMode("login")}
          >
            Login
          </button>
          <button
            type="button"
            className={mode === "register" ? "auth-tab active" : "auth-tab"}
            onClick={() => setMode("register")}
          >
            Register
          </button>
        </div>

        <form className="auth-form" onSubmit={onSubmit}>
          {isRegister && (
            <label>
              Full name
              <input
                className="auth-input"
                value={form.name}
                onChange={(e) => setForm((prev) => ({ ...prev, name: e.target.value }))}
                placeholder="Ada Nwosu"
                autoComplete="name"
              />
            </label>
          )}

          <label>
            Email address
            <input
              className="auth-input"
              type="email"
              value={form.email}
              onChange={(e) => setForm((prev) => ({ ...prev, email: e.target.value }))}
              placeholder="ada@example.com"
              autoComplete="email"
            />
          </label>

          <label>
            Password
            <input
              className="auth-input"
              type="password"
              value={form.password}
              onChange={(e) => setForm((prev) => ({ ...prev, password: e.target.value }))}
              placeholder="••••••••"
              autoComplete={isRegister ? "new-password" : "current-password"}
            />
          </label>

          {isRegister && (
            <label>
              Store name
              <input
                className="auth-input"
                value={form.company}
                onChange={(e) => setForm((prev) => ({ ...prev, company: e.target.value }))}
                placeholder="Ada Fashion House"
                autoComplete="organization"
              />
            </label>
          )}

          {error && <div className="auth-error">{error}</div>}

          <button className="auth-submit" type="submit" disabled={busy}>
            {busy ? "Working…" : isRegister ? "Create account" : "Login"}
          </button>
        </form>

        <div className="auth-foot">
          Demo access only. No server-side auth yet, so accounts persist in this browser for the sandbox.
        </div>
      </div>
    </div>
  );
}

function Bubble({ m }) {
  if (m.from === "system") {
    if (m.kind === "payment") {
      return (
        <div className="sys-wrap">
          <div className="sys-card">
            <div className="pay-title">💳 Complete your payment</div>
            <div className="pay-amt">₦{Number(m.amount || 0).toLocaleString()}</div>
            <a className="pay-btn" href={m.link || "#"} target="_blank" rel="noreferrer">
              Pay with OPay →
            </a>
            <div className="pay-ref">ref {m.reference}</div>
            <div className="pay-banner">🔒 Secured by OPay — no screenshots needed</div>
          </div>
        </div>
      );
    }
    return <div className="sys-line">{m.text}<span className="ts">{m.time}</span></div>;
  }

  const side = m.from === "customer" ? "right" : "left";
  return (
    <div className={`bubble-row ${side}`}>
      <div className={`bubble ${side}`}>
        {m.kind === "text" && <span>{m.text}</span>}
        {m.kind === "audio" && <audio controls src={m.url} />}
        {m.kind === "parsed" && <ParsedCard parsed={m.parsed} source={m.source} />}
        <span className="ts">{m.time}{side === "right" ? " ✓✓" : ""}</span>
      </div>
    </div>
  );
}

function ParsedCard({ parsed, source }) {
  return (
    <div className="parsed-card">
      <div className="parsed-title">
        📝 Order draft
        <span className={`chip conf-${parsed.confidence}`}>{parsed.confidence}</span>
        {source === "mock" && <span className="chip mock">mock</span>}
      </div>
      <ul>
        {parsed.items.map((it, i) => (
          <li key={i}>
            <b>{it.qty}×</b> {it.item}
            {it.size ? ` · size ${it.size}` : ""}
            {it.color ? ` · ${it.color}` : ""}
          </li>
        ))}
      </ul>
      <div className="parsed-meta">
        📍 {parsed.delivery_address || <i>(need address)</i>}
        {parsed.delivery_type ? ` · via ${parsed.delivery_type}` : ""}
      </div>
      {parsed.missing_fields?.length ? (
        <div className="parsed-warn">Missing: {parsed.missing_fields.join(", ")}</div>
      ) : (
        <div className="parsed-ok">Sent to seller for approval ✓</div>
      )}
    </div>
  );
}
